# Generated by Django 4.2.14 on 2024-09-28 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_fotografia_publicado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografia',
            old_name='publicado',
            new_name='publicada',
        ),
    ]
